### ISSUE TITLE
Time Zone issue

### ISSUE THREAD

**Issue by quentinl-c** [quentinl-c/TP_Book_Store#1]
(Short) error message : `A connection could not be obtained for driver class "null" and URL "null".  You may have specified an invalid URL.`

**Comment by quentinl-c** [comment]
Solution : 
```sql
SET @@global.time_zone = '+00:00';
SET @@session.time_zone = '+00:00';
```

**Comment by Naogiru** [comment]
Fonctionne de manière permanente en ajoutant :
```
?serverTimezone=UTC
``` 
derrière l'URL dans le fichier tomee.xml

**Comment by Naogiru** [comment]
Fonctionne de manière permanente en ajoutant : 
```
?serverTimezone=UTC
```
derrière l'URL du fichier tomee.xml
