### ISSUE TITLE
Unable to initialize agent

### ISSUE THREAD

**Issue by ALINO7903** [quentinl-c/TP_Book_Store#3]
## Solution
Cliquez sur "run" dans votre IDE-eclipse , puis choisissez "run configuration" et ajoutez dans "argument"  la ligne de code suivante:  `-Djdk.attach.allowAttachSelf=true`

**Comment by andre174u** [comment]
Erreur en utilisant -Djdk.attach.allowAttachSelf=true:
mars 03, 2020 10:51:56 AM jdk.internal.reflect.NativeMethodAccessorImpl invoke
WARNING: Bootstrap: command "-Djdk.attach.allowAttachSelf=true" does not exist.
